// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using InvestmentApp.Domain.Abstractions;
using System;
using System.Collections.Generic;

namespace InvestmentApp.Domain.Entities;

public sealed record Ticker : RecordEntity
{
    public int TickerId { get; set; }

    public string TickerSymbol { get; set; }

    public string Description { get; set; }
}